/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.util.Random;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author valeriazampetti
 */
public class PersonajeInterfaz extends javax.swing.JPanel {
     int contador;
    Random rand;

    /**
     * Creates new form PersonajeInterfaz
     */
    public PersonajeInterfaz() {
        initComponents();
        
        rand = new Random();
        this.contador = rand.nextInt(10) + 1;
        this.setOpaque(true); 
        this.setBackground(new Color(245, 230, 200));
        this.setForeground(Color.BLACK);
        Border border = new LineBorder(new Color(139, 69, 19), 2); 
        this.setBorder(border);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
